### ISSUE TITLE
Requirements Expansion

### ISSUE THREAD

**Issue by austin4195** [Daniel-Forge-Development/ForgeMenus#9]
Requirements as they are have been working great but are a bit limited. Introduction of the following things could make them even better!

1. Multiple Requirements - Having recursive menu support is fantastic but sometimes you need the ability to have multiple requirements would allow for greater flexibility
2. JS Expression support - Having the ability to use placeholders and parse them according to expressions would be great! For example: "%forgeeconomies_balance% >= 20"

**Comment by danorris709** [comment]
Added in 1.8.0
